### ISSUE TITLE
How to use it in webpack-dev mode

### ISSUE THREAD

**Issue by Jeff-Tian** [jsakas/markdown-to-react-loader#3]
It works great for webpack bundle it in production. But in the development, how import the `md` modules from jsx?

```
// index.jsx

import aModule from 'aModule.md'; // This will generate an error claiming: cannot find module aModule


```

I tried the demo code in your README.md, but it doesn't work in my side:

![image](https://user-images.githubusercontent.com/3367820/56359608-9f1f3000-6214-11e9-832a-5349f2eb833b.png)

![image](https://user-images.githubusercontent.com/3367820/56359621-a9d9c500-6214-11e9-8022-70c8de21f2fe.png)

Is it related to TypeScript?

**Comment by jsakas** [comment]
Closed by https://github.com/jsakas/markdown-to-react-loader/pull/2
